import { Geist, Geist_Mono, Poppins } from "next/font/google";
import '../globals.css';
import Sidebar from "@/components/Sidebar";
import Search from "@/components/Search";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}>
        <div className="bg-[#f5f7f8] grid grid-cols-12 gap-8">
          <div className="col-span-3">
            <Sidebar />
          </div>
          <div className="col-span-9 mt-10 pr-10 overflow-auto no-scrollbar">
            <Search />
            <div className="h-full bg-white rounded-3xl mt-10">
              <div className="p-10">
                <div className="border-b-1 pb-5 border-[#409aa5] flex justify-between items-center">
                  <button className="bg-[#f5f7f8] p-3 rounded-xl font-bold text-[#409aa5]">
                    All Books
                  </button>
                  {/* <form class="max-w-sm w-64">
                    <select id="countries" class="bg-gray-100 rounded-xl border-none  text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                      <option selected>select categories</option>
                      <option value="US">United States</option>
                      <option value="CA">Canada</option>
                      <option value="FR">France</option>
                      <option value="DE">Germany</option>
                    </select>
                  </form> */}
                </div>
              {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
