import { Geist, Geist_Mono, Poppins } from "next/font/google";
import '../globals.css';

import Sidebar from "@/components/Sidebar";
import Search from "@/components/Search";
import ButtonType from "@/components/ButtonType";
import SelectCategoriesPage from "@/components/SelectCategoriesPage";
import PathBasedVisibility from "@/components/PathBasedVisibility";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}>
        <div className="bg-[#f5f7f8] grid grid-cols-12 gap-8">
          <div className="col-span-3">
            <Sidebar />
          </div>
          <div className="col-span-9 mt-10 pr-10 pl-2 overflow-auto no-scrollbar">
            <Search />
            <div className="h-full bg-white rounded-3xl mt-10">
              <div className="p-10">
                <PathBasedVisibility />
                <div className="border-b-1 pb-5 border-[#409aa5] flex justify-between items-center">
                  <ButtonType />
                  <div className="hide-on-home">
                    <SelectCategoriesPage />
                  </div>
                </div>
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
